extends:
  - react-app
  - ../.eslintrc.yml
parserOptions:
  project:
    - ./tsconfig.json
    - ./tsconfig.node.json
overrides:
  - files:
      - vite.config.ts
    parserOptions:
      project: ./tsconfig.node.json
