extends:
  - react-app
  - ../.eslintrc.yml
parserOptions:
  project:
    - ./tsconfig.json
    - ./tsconfig.node.json
overrides:
  - files:
      - vite.config.ts
    parserOptions:
      project: ./tsconfig.node.json
rules:
  '@typescript-eslint/no-restricted-imports':
    - error
    - patterns:
        - group:
            - '@BLOGS/backend/**'
            - '!@BLOGS/backend/**/'
            - '!@BLOGS/backend/**/input'
            - '!@BLOGS/backend/src/utils/canBlockedPost'
          allowTypeImports: true
          message: 'Из внутреннего рабочего пространства разрешено импортировать только типы и схемы ввода.'
